### ISSUE TITLE
Gladys doesn't keep the MQTT Brocker URL after docker restart when using docker-compose

### ISSUE THREAD

**Issue by magarcia** [GladysAssistant/Gladys#1647]
**Describe the bug**
When running Docker Gladys with docker compose every time the container is restarted the MQTT configuration doesn't load (although is still saved in the database).

**To Reproduce**

1. With a docker compose file like this:
```yml
# docker-compose.yml
version: "3.3"
services:
  gladys:
    restart: always
    privileged: true 
    network_mode: host
    container_name: gladys
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8090
      - TZ=Europe/Madrid
      - SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCAL_DATA_DIR}/gladys:/var/lib/gladysassistant"
      - "/dev:/dev"
      - "/run/udev:/run/udev:ro"
    image: "gladysassistant/gladys:v4"
  mosquitto:
    restart: always
    container_name: mosquitto
    image: eclipse-mosquitto:2
    volumes:
      - ${LOCAL_DATA_DIR}/mosquitto/config/:/mosquitto/config/
      - ${LOCAL_DATA_DIR}/mosquitto/log/:/mosquitto/log/
      - ${LOCAL_DATA_DIR}/mosquitto/data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
```
3. Go to `<gladys-server-domain>/dashboard/integration/device/mqtt/setup`
4. Setup the Broker URL to `mqtt://localhost`
5. Everything should work fine
6. Restart the Gladys container
7. Go to `<gladys-server-domain>/dashboard/integration/device/mqtt/setup`
8. The Broker URL is lost

**Expected behavior**
It should keep loading the Broker URL after restart.

**Your Gladys installation (please complete the following information):**
- Raspberry Pi 4 
- Debian GNU/Linux 11 (bullseye)
- Docker version 20.10.20, build 9fdeb9c

**Additional context**
When restarting the Docker container this logs are shown:
```
<warn> service.start.js:44 (Service.start) Unable to start service zigbee2mqtt PlatformNotCompatible [Error]: DOCKER_CGROUP_CONTAINER_ID_NOT_AVAILABLE
    at System.getGladysContainerId (/src/server/lib/system/system.getGladysContainerId.js:45:13)
    at System.getNetworkMode (/src/server/lib/system/system.getNetworkMode.js:16:25)
    at Zigbee2mqttManager.init (/src/server/services/zigbee2mqtt/lib/init.js:18:23)
    at Object.start (/src/server/services/zigbee2mqtt/index.js:17:5)
    at Service.start (/src/server/lib/service/service.start.js:33:7)
```

After some research I found [this Stackoverflow entry](https://stackoverflow.com/questions/68816329/how-to-get-docker-container-id-from-within-the-container-with-cgroup-v2) which lead me to verify that `/proc/self/cgroup` is actually empty.
The issue can be solved when running docker using the `--cid` or `--cgroupns` flag, but none of those options is available in docker compose.
