### ISSUE TITLE
Le chat du dashboard ne reçois pas les réponses de Gladys

### ISSUE THREAD

**Issue by Dremor** [GladysAssistant/Gladys#250]
Bonjour,

J'ai ajouté une box "Chat" au dashboard, mais celui-ci ne fonctionne pas bien. Il est possible d'y écrire (il y a cependant parfois une certaine latence), mais la réponse de Gladys ne s'affiche pas, à moins de rafraichir la page.

J'ai installé Gladys sur un serveur dédié (en me basant sur le docker-compose personnalisé), derrière un reverse-proxy https HAPROXY, qui sert l'ui de Gladys via le port 443 (le port 80 redirige directement vers celui-ci via un HTTP 301).

conf (partielle) HAPROXY : 

```
frontend 443
    http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains"
    http-response set-header X-XSS-Protection "1; mode=block"
    http-response set-header X-Frame-Options "ALLOW-FROM <redacted>"
    http-response set-header X-Content-Type-Options "nosniff"
    http-response set-header Referrer-Policy "no-referrer"
    rspirep ^(set-cookie:.*)  \1;\ Secure
frontend 80
    redirect scheme https code 301 if !{ ssl_fc }
```

docker-compose.yml : 
``` yaml
version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: 
      MYSQL_PASSWORD: 
      MYSQL_USER: 
    volumes_from:
    - sql-data
  sql-data:
    image: busybox
    entrypoint:
    - /bin/true
    volumes:
    - gladys-sql:/var/lib/mysql
  core:
    image: gladysproject/gladys
    environment:
      MYSQL_HOST: db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: 
    entrypoint:
    - bash
    - -c
    - node init.js && node app.js
    links:
    - mariadb:db
```
