### ISSUE TITLE
Gladys does not run under Kubernetes

### ISSUE THREAD

**Issue by nmaupu** [GladysAssistant/Gladys#609]
**Describe the bug**
When deploying gladys under kubernetes, it fails to start.

**To Reproduce**
Use the following manifests:
```
---
# Source: gladys/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g-gladys
  labels:
    app.kubernetes.io/name: gladys
    helm.sh/chart: gladys-0.1.0
    app.kubernetes.io/instance: g
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
---
# Source: gladys/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: g-gladys
  labels:
    app.kubernetes.io/name: gladys
    helm.sh/chart: gladys-0.1.0
    app.kubernetes.io/instance: g
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gladys
    app.kubernetes.io/instance: g
---
# Source: gladys/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g-gladys
  labels:
    app.kubernetes.io/name: gladys
    helm.sh/chart: gladys-0.1.0
    app.kubernetes.io/instance: g
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gladys
      app.kubernetes.io/instance: g
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gladys
        app.kubernetes.io/instance: g
    spec:
      serviceAccountName: g-gladys
      securityContext:{}
      containers:
        - name: gladys
          securityContext:{}
          image: "gladysassistant/gladys:4.0.0-beta-amd64"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: production
            - name: SERVER_PORT
              value: "80"
            - name: TZ
              value: Europe/Paris
            - name: SQLITE_FILE_PATH
              value: /var/lib/gladysassistant/gladys-production.db
          volumeMounts:
            - name: db
              mountPath: /var/lib/gladysassistant
            - name: logs
              mountPath: /root/.npm/_logs/
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 45
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

      volumes:
        - name: db
          emptyDir: {}
        - name: logs
          emptyDir: {}
---
# Source: gladys/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: g-gladys
  labels:
    app.kubernetes.io/name: gladys
    helm.sh/chart: gladys-0.1.0
    app.kubernetes.io/instance: g
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  rules:
    - host: "gladys.home"
      http:
        paths:
          - path: /
            backend:
              serviceName: g-gladys
              servicePort: 80
```

**Expected behavior**
Gladys starts successfully.

**Your Gladys installation (please complete the following information):**

- Kubernetes version 1.16.1
- Docker version 18.06.2-ce

**Additional context**
Here is the pod logs :
```
> gladys-server@ start:prod /src/server
> npm run db-migrate:prod && cross-env NODE_ENV=production node index.js


> gladys-server@ db-migrate:prod /src/server
> cross-env NODE_ENV=production node_modules/.bin/sequelize db:migrate


Sequelize CLI [Node: 12.13.0, CLI: 5.5.1, ORM: 4.44.3]

Loaded configuration file "config/config.js".
Using environment "production".
No migrations were executed, database schema was already up to date.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gladys-server@ start:prod: `npm run db-migrate:prod && cross-env NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gladys-server@ start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-18T01_03_42_470Z-debug.log
```

I used an `emptyDir` to be able to access the log file (under `/root/.npm/_logs`) when the pod crashes and restarts.
Here is the content:
```
/src/server # cat /root/.npm/_logs/2019-11-18T01_03_42_470Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start:prod' ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prestart:prod', 'start:prod', 'poststart:prod' ]
5 info lifecycle gladys-server@~prestart:prod: gladys-server@
6 info lifecycle gladys-server@~start:prod: gladys-server@
7 verbose lifecycle gladys-server@~start:prod: unsafe-perm in lifecycle true
8 verbose lifecycle gladys-server@~start:prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/src/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle gladys-server@~start:prod: CWD: /src/server
10 silly lifecycle gladys-server@~start:prod: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run db-migrate:prod && cross-env NODE_ENV=production node index.js'
10 silly lifecycle ]
11 silly lifecycle gladys-server@~start:prod: Returned: code: 1  signal: null
12 info lifecycle gladys-server@~start:prod: Failed to exec start:prod script
13 verbose stack Error: gladys-server@ start:prod: `npm run db-migrate:prod && cross-env NODE_ENV=production node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid gladys-server@
15 verbose cwd /src/server
16 verbose Linux 4.15.0-70-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:prod"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error gladys-server@ start:prod: `npm run db-migrate:prod && cross-env NODE_ENV=production node index.js`
22 error Exit status 1
23 error Failed at the gladys-server@ start:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Moreover, from the documentation I see the following for docker usage:
- Docker socket mounted
- `/dev` mounted
- container privileged
- host network used

For obvious security reasons, I don't want to run Gladys with those options. What are they used for ? I guess, they are used for auto-upgrade or something similar. hostNetwork option seems to be used to easily access web-ui. As I am using kubernetes, I will be using a simple ingress controller.

My main concern is to be able to run Gladys from a Kubernetes cluster which should be very easy as Gladys is already made to be run under Docker.
I am not very familiar with nodeJS so pardon my ignorance if I am missing something obvious :)
